# @package _group_
network:
  model: "CXRdecomp"
  use_norm: "none"
  activation_func: "leakyRelu"
  input_views: 3

general:
  batch_size: 1
  learning_rate: 0.00003
  loss: "Combined"
  overfit_batches: 0
  data_aug: false
