# @package _group_
network:
  model: "CXRdecomp6"
  use_norm: "none"
  activation_func: "leakyRelu"
  input_views: 2

general:
  batch_size: 1
  learning_rate: 0.00001
  loss: "L2"
  overfit_batches: 0
  data_aug: false
